utility = {
    'crew_size': 10,
    'metabolic_profile': 10,
    'metabolic_rate': 10,
    'meteorite_impact_a': 1,
    'meteorite_impact_b': 1,
    'insulation_loss': 1,
    'airlock_failure': 1,
    'ihab_config': 10,
    'halo_config': 1,
    'co2_scrub_fault': 1,
    'half_cycle_time': 1,
    'vacuum_severity': 1,
    'vacuum_fault': 1,
    'flow_rate_a': 1,
    'flow_rate_b': 1,
    'mesh_size': 1,
    'filter_clog_fault': 1,
    'lstm_param_filter': 1,
    'screen_blinding': 1,
    'leak_severity': 1,
    'leak_fault': 1,
    'valve_severity': 1,
    'valve_fault': 1,
    'bed_length_a': 10,
    'bed_length_b': 10,
    'pellet_bed_ratio': 1,
    'water_preload': 0.5,
    'system_leak': 1,
    'heater_failure': 1,
    'heater_fault_a': 1,
    'diffuser': 0.9,
    'airflow_rate': 0.9,
    'fan': 0.9,
    'oxygen_fault': 1,
    'fire': 1,
    'water_fault': 1,
    'humidity_fault': 1,
    'inlet_humidity': 0.5,
    'inlet_temperature': 0.5,
    'heater_fault_b': 1,
    'evaporator_fault': 1,
    'compressor_fault': 0.5
}

observability = {
    'count': 1,
    'crew': 1,
    'activity': 1,
    'GATEWAY': 1,
    'module': 1,
    'structure': 1,
    'PPE': 1,
    'IHAB': 1,
    'HALO': 0.5,
    'ECLSS': 1,

    'CDRS': 1,

    'pipe': 1,
    'filter': 1,
    'valve': 1,
    'bed': 1,
    'size': 0.5,
    'water': 1,
    'heater': 1,

    'ACV': 1,
    'OGA': 1,
    'FDS': 1,
    'WPA': 1,
    'THCS': 1,
    'inlet': 1,
    'air_heater': 0.5,
    'evaporator': 1,
    'compressor': 1
}

knowledge = {
    ("ECLSS", "PPE"): 10,
    ("ECLSS", "IHAB"): 10,
    ("ECLSS", "HALO"): 10,
    ("PPE", "module"): 10,
    ("IHAB", "module"): 10,
    ("HALO", "module"): 10,
    ("count", "crew"): 10,
    ("count", "crew_size"): 10,
    ("activity", "crew"): 10,
    ("activity", "metabolic_profile"): 10,
    ("activity", "metabolic_rate"): 10,
    ("crew", "GATEWAY"): 10,
    ("structure", "meteorite_impact_a"): 0,
    ("structure", "meteorite_impact_b"): 10,
    ("structure", "insulation_loss"): 10,
    ("structure", "airlock_failure"): 10,
    ("structure", "module"): 10,
    ("pipe", "vacuum_severity"): 10,
    ("pipe", "vacuum_fault"): 10,
    ("pipe", "flow_rate_a"): 10,
    ("pipe", "flow_rate_b"): 10,
    ("pipe", "CDRS"): 10,
    ("filter", "mesh_size"): 10,
    ("filter", "filter_clog_fault"): 10,
    ("filter", "lstm_param_filter"): 10,
    ("filter", "screen_blinding"): 10,
    ("filter", "CDRS"): 10,
    ("valve", "leak_severity"): 10,
    ("valve", "leak_fault"): 10,
    ("valve", "valve_severity"): 10,
    ("valve", "valve_fault"): 10,
    ("valve", "CDRS"): 10,
    ("size", "bed"): 10,
    ("size", "bed_length_a"): 10,
    ("size", "bed_length_b"): 10,
    ("size", "pellet_bed_ratio"): 10,
    ("water", "bed"): 10,
    ("water", "water_preload"): 0,
    ("water", "system_leak"): 10,
    ("bed", "CDRS"): 10,
    ("heater", "heater_failure"): 10,
    ("heater", "heater_fault_a"): 10,
    ("heater", "CDRS"): 10,
    ("CDRS", "ECLSS"): 10,
    ("ACV", "ECLSS"): 10,
    ("ACV", "diffuser"): 0,
    ("ACV", "airflow_rate"): 10,
    ("ACV", "fan"): 10,
    ("OGA", "ECLSS"): 10,
    ("OGA", "oxygen_fault"): 10,
    ("FDS", "ECLSS"): 10,
    ("FDS", "fire"): 10,
    ("WPA", "ECLSS"): 10,
    ("WPA", "water_fault"): 10,
    ("inlet", "THCS"): 10,
    ("inlet", "inlet_humidity"): 10,
    ("inlet", "inlet_temperature"): 10,
    ("air_heater", "THCS"): 10,
    ("air_heater", "heater_fault_b"): 10,
    ("evaporator", "THCS"): 10,
    ("evaporator", "evaporator_fault"): 10,
    ("compressor", "THCS"): 10,
    ("compressor", "compressor_fault"): 10,
    ("THCS", "ECLSS"): 10,
    ("THCS", "humidity_fault"): 10,
    ("ECLSS", "co2_scrub_fault"): 10,
    ("ECLSS", "half_cycle_time"): 10,
    ("IHAB", "ihab_config"): 10,
    ("HALO", "halo_config"): 10,
    ("module", "GATEWAY"): 10
}

